### ISSUE TITLE
Changing Ownership

### ISSUE THREAD

**Issue by lnxpy** [ghost1372/CodeHubDesktop#1]
Hey Mehdi,

Hope you doing well. I wanted to suggest you to change the ownership of CodeHubDesktop to CodeHub-Contributors, so It lets us to manage teams and collaborate on projects better than locally. 

Hope hear from you soon.
Thanks :) :heart:

**Comment by ghost1372** [comment]
Hi @lnxpy 
no problem, first you should delete this repo
https://github.com/CodeHub-Contributors/CodeHubDesktop
because repo already exist and github cant change ownership.

![Untitled](https://user-images.githubusercontent.com/9213496/79045580-1b2e3700-7c21-11ea-80d5-32c03e7c0dfc.png)

**Comment by lnxpy** [comment]
That's it.
It's all done.

**Comment by ghost1372** [comment]
Done 😉
