### ISSUE TITLE
list of languages

### ISSUE THREAD

**Issue by ghost1372** [ghost1372/CodeHubDesktop#2]
@lnxpy  Can you Send the list of available languages as a text file?
I had previously extracted the list of languages from ComboBox.
I found that the name of the language displayed in Combobox differs from the name stored in the script.
![0x](https://user-images.githubusercontent.com/9213496/79046043-a5779a80-7c23-11ea-99af-bae0e0ddea9a.png)

![1x](https://user-images.githubusercontent.com/9213496/79046055-bb855b00-7c23-11ea-8bc5-a6b1f00bdb23.png)

**Comment by lnxpy** [comment]
For sure. Take a look at [this](https://github.com/CodeHub-Contributors/CodeHub-cli/blob/master/components.py) script. 
You can extract all languages from tha Language class. :)

**Comment by ghost1372** [comment]
@lnxpy  tnx

**Comment by lnxpy** [comment]
How fast you answer 😁😎❤️
Would you please add the installation section in the readme to build it up on my system? 

Good luck dear.

**Comment by ghost1372** [comment]
@lnxpy  😁 
I will add soon

**Comment by ghost1372** [comment]
@lnxpy  Readme Updated with build instracture
